version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_server
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: image-server
    depends_on:
      - db
    ports:
      - "3100:3100"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/image_server"

volumes:
  pg_data:
